export interface AIPromptItem {
  id: string;
  title: string;
  prompt: string;
  category:
    | "Cloud Architecture"
    | "Microservices"
    | "Databases"
    | "DevOps"
    | "Web3"
    | "AI & ML"
    | "Cybersecurity"
    | "High-Scale"
    | "Serverless"
    | "Fintech";
  complexity: "Beginner" | "Intermediate" | "Advanced" | "Enterprise";
  tags: string[];
}

export const AI_PROMPT_CATEGORIES = [
  "All",
  "Cloud Architecture",
  "Microservices",
  "Databases",
  "DevOps",
  "Web3",
  "AI & ML",
  "Cybersecurity",
  "High-Scale",
  "Serverless",
  "Fintech",
] as const;

export const AI_PROMPT_LIBRARY: AIPromptItem[] = [
  // ── Requested Daily-Use Featured Commands ──
  {
    id: "daily-user-login-sequence",
    title: "Basic User Login Sequence",
    prompt: "Basic User Login Sequence",
    category: "Cybersecurity",
    complexity: "Beginner",
    tags: ["Auth", "JWT", "Session", "Security", "Login"],
  },
  {
    id: "daily-forgot-password-flow",
    title: "Forgot Password Flow",
    prompt: "Forgot Password Flow",
    category: "Cybersecurity",
    complexity: "Beginner",
    tags: ["Auth", "Password Reset", "Email", "Token"],
  },
  {
    id: "daily-rest-crud-architecture",
    title: "REST API CRUD Architecture",
    prompt: "REST API CRUD Architecture",
    category: "Microservices",
    complexity: "Beginner",
    tags: ["REST", "API", "CRUD", "FastAPI", "Express"],
  },
  {
    id: "daily-ecommerce-cart-flow",
    title: "Simple E-commerce Cart Flow",
    prompt: "Simple E-commerce Cart Flow",
    category: "Fintech",
    complexity: "Intermediate",
    tags: ["E-commerce", "Cart", "Checkout", "Inventory"],
  },
  {
    id: "daily-blog-database-schema",
    title: "Blog Database Schema",
    prompt: "Blog Database Schema",
    category: "Databases",
    complexity: "Beginner",
    tags: ["Database", "SQL", "Postgres", "Schema", "Tables"],
  },
  {
    id: "daily-k8s-topology",
    title: "Scalable Kubernetes Cluster Topology",
    prompt: "Design a scalable Kubernetes cluster topology",
    category: "DevOps",
    complexity: "Enterprise",
    tags: ["Kubernetes", "K8s", "Ingress", "Pods", "Microservices"],
  },
  {
    id: "daily-stripe-webhook",
    title: "Stripe Webhook Payment Flow",
    prompt: "Map out a Stripe webhook payment flow",
    category: "Fintech",
    complexity: "Intermediate",
    tags: ["Stripe", "Webhooks", "Payments", "Idempotency", "Queue"],
  },
  {
    id: "daily-redis-pubsub",
    title: "Redis Pub/Sub Caching Architecture",
    prompt: "Create a Redis Pub/Sub caching architecture",
    category: "Databases",
    complexity: "Advanced",
    tags: ["Redis", "PubSub", "Cache", "Realtime", "In-Memory"],
  },

  // ── 1. Cloud Architecture ──
  {
    id: "cloud-1",
    title: "AWS Multi-Tier Microservices with Lambda & API Gateway",
    prompt: "Generate a scalable AWS microservices architecture with API Gateway and Lambda.",
    category: "Cloud Architecture",
    complexity: "Advanced",
    tags: ["AWS", "Lambda", "API Gateway", "DynamoDB"],
  },
  {
    id: "cloud-2",
    title: "AWS Multi-Region Active-Active Disaster Recovery",
    prompt: "Design an AWS multi-region active-active deployment using Route 53 latency routing, DynamoDB Global Tables, and S3 Cross-Region Replication.",
    category: "Cloud Architecture",
    complexity: "Enterprise",
    tags: ["AWS", "Route53", "Multi-Region", "S3"],
  },
  {
    id: "cloud-3",
    title: "GCP Global Hybrid-Cloud VPC Peering",
    prompt: "Architect a Google Cloud Platform hybrid-cloud infrastructure connecting on-premises data center via Cloud Interconnect with Cloud Armor, Load Balancing, and GKE.",
    category: "Cloud Architecture",
    complexity: "Enterprise",
    tags: ["GCP", "GKE", "Hybrid Cloud", "Cloud Armor"],
  },
  {
    id: "cloud-4",
    title: "Azure Enterprise Hub-and-Spoke Network",
    prompt: "Design an Azure enterprise hub-and-spoke VNet topology featuring Azure Firewall, Bastion, ExpressRoute gateway, and isolated spoke networks for production and staging.",
    category: "Cloud Architecture",
    complexity: "Enterprise",
    tags: ["Azure", "Hub-Spoke", "Firewall", "Networking"],
  },
  {
    id: "cloud-5",
    title: "AWS Static Web App with Global CDN & WAF",
    prompt: "Build an AWS static website architecture using S3 bucket origin, CloudFront CDN edge distribution, ACM SSL certificate, and AWS WAF rate limiting.",
    category: "Cloud Architecture",
    complexity: "Beginner",
    tags: ["CloudFront", "S3", "WAF", "CDN"],
  },
  {
    id: "cloud-6",
    title: "Multi-Cloud Kubernetes Management with Anthos",
    prompt: "Design a multi-cloud container orchestration strategy spanning AWS EKS and GCP GKE managed centrally via Google Anthos with unified service mesh telemetry.",
    category: "Cloud Architecture",
    complexity: "Enterprise",
    tags: ["Anthos", "EKS", "GKE", "Istio"],
  },
  {
    id: "cloud-7",
    title: "AWS CloudTrail & GuardDuty Security Audit Hub",
    prompt: "Construct an AWS security lake ingesting VPC Flow Logs, CloudTrail, and GuardDuty alerts forwarded to EventBridge, AWS Security Hub, and centralized OpenSearch.",
    category: "Cloud Architecture",
    complexity: "Advanced",
    tags: ["AWS", "Security", "GuardDuty", "OpenSearch"],
  },
  {
    id: "cloud-8",
    title: "Cloudflare Edge Compute with KV & D1 Database",
    prompt: "Architect a modern JAMstack platform deployed on Cloudflare Workers edge nodes utilizing Workers KV for caching, D1 SQL database, and R2 object storage.",
    category: "Cloud Architecture",
    complexity: "Intermediate",
    tags: ["Cloudflare", "Workers", "Edge", "D1"],
  },
  {
    id: "cloud-9",
    title: "AWS ECS Fargate Containerized Web Fleet",
    prompt: "Design a serverless container architecture on AWS ECS Fargate with Application Load Balancer, auto-scaling target tracking, and RDS Aurora Serverless v2.",
    category: "Cloud Architecture",
    complexity: "Intermediate",
    tags: ["ECS", "Fargate", "ALB", "Aurora"],
  },
  {
    id: "cloud-10",
    title: "GCP BigQuery Enterprise Data Lakehouse",
    prompt: "Model an enterprise data lakehouse in GCP ingesting streaming logs into Pub/Sub, processing with Dataflow, storing raw data in Cloud Storage, and analytical views in BigQuery.",
    category: "Cloud Architecture",
    complexity: "Advanced",
    tags: ["GCP", "BigQuery", "Dataflow", "PubSub"],
  },

  // ── 2. Microservices ──
  {
    id: "micro-1",
    title: "Event-Driven Kafka Streaming Data Pipeline",
    prompt: "Create an event-driven Kafka streaming data pipeline.",
    category: "Microservices",
    complexity: "Advanced",
    tags: ["Kafka", "Event-Driven", "Streaming", "CDC"],
  },
  {
    id: "micro-2",
    title: "CQRS & Event Sourcing Architecture",
    prompt: "Design a CQRS (Command Query Responsibility Segregation) microservices system with EventStoreDB for write commands, Kafka messaging, and MongoDB read models.",
    category: "Microservices",
    complexity: "Enterprise",
    tags: ["CQRS", "Event Sourcing", "Kafka", "MongoDB"],
  },
  {
    id: "micro-3",
    title: "Saga Pattern Distributed Transaction Coordinator",
    prompt: "Model an e-commerce checkout workflow using the Saga orchestration pattern with Temporal.io / AWS Step Functions coordinating Payment, Inventory, and Shipping microservices.",
    category: "Microservices",
    complexity: "Enterprise",
    tags: ["Saga", "Distributed Transactions", "Temporal", "Microservices"],
  },
  {
    id: "micro-4",
    title: "Envoy Service Mesh with Istio & Mutual TLS",
    prompt: "Design a zero-trust Kubernetes service mesh architecture using Istio and Envoy sidecars with automatic mTLS, traffic mirroring, canary deployments, and Jaeger tracing.",
    category: "Microservices",
    complexity: "Advanced",
    tags: ["Istio", "Envoy", "mTLS", "Kubernetes"],
  },
  {
    id: "micro-5",
    title: "GraphQL Federation Gateway across Microservices",
    prompt: "Architect an Apollo Federation GraphQL Gateway composing distinct subgraphs (User, Product, Order, Review) with sub-second entity caching and rate-limiting.",
    category: "Microservices",
    complexity: "Advanced",
    tags: ["GraphQL", "Apollo", "Federation", "NodeJS"],
  },
  {
    id: "micro-6",
    title: "BFF (Backend-for-Frontend) Architecture",
    prompt: "Design a Backend-For-Frontend (BFF) topology separating Mobile API Gateway from Web Portal API Gateway, each aggregating tailored microservice payloads.",
    category: "Microservices",
    complexity: "Intermediate",
    tags: ["BFF", "API Gateway", "Mobile", "Web"],
  },
  {
    id: "micro-7",
    title: "Asynchronous Webhook Ingestion & Dead-Letter Queue",
    prompt: "Create a resilient webhook ingestion service that buffers spikes into RabbitMQ, processes with distributed consumer workers, and routes failures to a Dead Letter Queue (DLQ).",
    category: "Microservices",
    complexity: "Intermediate",
    tags: ["RabbitMQ", "Webhooks", "DLQ", "Workers"],
  },
  {
    id: "micro-8",
    title: "Microservices Outbox Pattern for Zero Data Loss",
    prompt: "Diagram a transactional outbox pattern using PostgreSQL transactional logs, Debezium CDC engine, and Apache Kafka for reliable cross-service domain publishing.",
    category: "Microservices",
    complexity: "Advanced",
    tags: ["Outbox Pattern", "Debezium", "Kafka", "PostgreSQL"],
  },
  {
    id: "micro-9",
    title: "Distributed Rate Limiter with Redis Token Bucket",
    prompt: "Design a global distributed rate limiter middleware employing Redis Lua scripts and sliding window counter algorithm protecting downstream microservices.",
    category: "Microservices",
    complexity: "Intermediate",
    tags: ["Rate Limiter", "Redis", "Lua", "Gateway"],
  },
  {
    id: "micro-10",
    title: "Circuit Breaker & Bulkhead Fault-Tolerance Mesh",
    prompt: "Model resilient service-to-service communication with Resilience4j circuit breakers, bulkhead isolation pools, and fallback static degraded caches.",
    category: "Microservices",
    complexity: "Intermediate",
    tags: ["Resilience4j", "Circuit Breaker", "Fault Tolerance"],
  },

  // ── 3. Databases ──
  {
    id: "db-1",
    title: "High-Availability PostgreSQL Cluster with Redis Caching",
    prompt: "Design a high-availability PostgreSQL database cluster with Redis caching.",
    category: "Databases",
    complexity: "Advanced",
    tags: ["PostgreSQL", "Redis", "High Availability", "Patroni"],
  },
  {
    id: "db-2",
    title: "Distributed CockroachDB Multi-Region Geo-Partitioning",
    prompt: "Architect a globally distributed CockroachDB cluster using row-level geo-partitioning to ensure EU user data complies with GDPR while maintaining low-latency local reads.",
    category: "Databases",
    complexity: "Enterprise",
    tags: ["CockroachDB", "GDPR", "Geo-Replication", "SQL"],
  },
  {
    id: "db-3",
    title: "Redis Cluster with Read Replicas & Sentinel Failover",
    prompt: "Diagram an in-memory Redis 7.0 Cluster featuring automatic Sentinel failover, 3 master nodes, 6 read replicas, and write-through cache invalidation.",
    category: "Databases",
    complexity: "Intermediate",
    tags: ["Redis", "Sentinel", "Caching", "Failover"],
  },
  {
    id: "db-4",
    title: "ClickHouse Real-Time Analytics OLAP Engine",
    prompt: "Design a high-volume analytical ingest pipeline feeding billions of clickstream events daily from Kafka into ClickHouse partitioned by date with Grafana dashboards.",
    category: "Databases",
    complexity: "Advanced",
    tags: ["ClickHouse", "OLAP", "Kafka", "Analytics"],
  },
  {
    id: "db-5",
    title: "MongoDB Atlas Sharded Cluster with Global Search",
    prompt: "Create a MongoDB Atlas sharded cluster architecture with custom hashed shard keys, automated balancer, and Atlas Search vector index integration.",
    category: "Databases",
    complexity: "Advanced",
    tags: ["MongoDB", "Sharding", "NoSQL", "Search"],
  },
  {
    id: "db-6",
    title: "Cassandra Masterless Wide-Column Time-Series Store",
    prompt: "Architect an Apache Cassandra / ScyllaDB multi-datacenter cluster optimized for IoT high-frequency sensor writes with tunable consistency (QUORUM).",
    category: "Databases",
    complexity: "Enterprise",
    tags: ["Cassandra", "ScyllaDB", "IoT", "Time-Series"],
  },
  {
    id: "db-7",
    title: "Neo4j Graph Database for Social Graph & Recommendations",
    prompt: "Model a social network graph database schema in Neo4j with relationship traversal queries for fraud ring detection and friend-of-friend recommendations.",
    category: "Databases",
    complexity: "Intermediate",
    tags: ["Neo4j", "Graph", "Fraud Detection", "Cypher"],
  },
  {
    id: "db-8",
    title: "Elasticsearch Distributed Search & Log Analytics Cluster",
    prompt: "Design an Elasticsearch enterprise cluster featuring dedicated master nodes, hot-warm-cold data tiering, and cross-cluster replication (CCR).",
    category: "Databases",
    complexity: "Advanced",
    tags: ["Elasticsearch", "Search", "CCR", "Hot-Warm"],
  },
  {
    id: "db-9",
    title: "DynamoDB Single-Table Design with GSI Optimization",
    prompt: "Architect an AWS DynamoDB single-table design using partition keys, sort keys, sparse global secondary indexes (GSIs), and DynamoDB Streams for audit replication.",
    category: "Databases",
    complexity: "Advanced",
    tags: ["DynamoDB", "Single Table", "NoSQL", "AWS"],
  },
  {
    id: "db-10",
    title: "Zero-Downtime Database Migration with Flyway & CDC",
    prompt: "Diagram a dual-write blue-green database migration strategy using Debezium CDC and Flyway schema versioning to migrate from MySQL to PostgreSQL without downtime.",
    category: "Databases",
    complexity: "Enterprise",
    tags: ["Flyway", "CDC", "Migration", "Zero-Downtime"],
  },

  // ── 4. DevOps ──
  {
    id: "devops-1",
    title: "GitOps Continuous Delivery with ArgoCD & Kubernetes",
    prompt: "Design an enterprise GitOps continuous delivery pipeline using GitHub Actions, Helm charts, ArgoCD, and multi-cluster Kubernetes environments.",
    category: "DevOps",
    complexity: "Advanced",
    tags: ["GitOps", "ArgoCD", "Kubernetes", "Helm"],
  },
  {
    id: "devops-2",
    title: "Observability Stack: Prometheus, Grafana & Loki",
    prompt: "Architect a centralized Kubernetes observability stack combining Prometheus metric scraping, Grafana dashboards, Promtail, and Loki log aggregation.",
    category: "DevOps",
    complexity: "Intermediate",
    tags: ["Prometheus", "Grafana", "Loki", "Observability"],
  },
  {
    id: "devops-3",
    title: "OpenTelemetry Distributed Tracing Mesh with Jaeger",
    prompt: "Design an end-to-end distributed tracing telemetry pipeline utilizing OpenTelemetry collector agents, OTLP protocols, and Jaeger visualization backend.",
    category: "DevOps",
    complexity: "Advanced",
    tags: ["OpenTelemetry", "Jaeger", "Tracing", "APM"],
  },
  {
    id: "devops-4",
    title: "HashiCorp Vault Secret Management with K8s Sidecars",
    prompt: "Model a secure secrets rotation infrastructure using HashiCorp Vault server in HA mode, Consul storage backend, and Kubernetes Vault Agent Injector sidecars.",
    category: "DevOps",
    complexity: "Enterprise",
    tags: ["Vault", "Security", "Secrets", "Consul"],
  },
  {
    id: "devops-5",
    title: "Infrastructure as Code (IaC) with Terraform & Terragrunt",
    prompt: "Structure a modular Terraform and Terragrunt deployment pipeline provisioning multi-environment AWS VPC, RDS, EKS, and IAM policies with remote S3 state locks.",
    category: "DevOps",
    complexity: "Intermediate",
    tags: ["Terraform", "Terragrunt", "IaC", "AWS"],
  },
  {
    id: "devops-6",
    title: "Zero-Downtime Canary Release with Flagger & Linkerd",
    prompt: "Design an automated canary release strategy using Flagger operator, Linkerd service mesh, and Prometheus metric thresholds for automated rollbacks.",
    category: "DevOps",
    complexity: "Advanced",
    tags: ["Canary", "Flagger", "Linkerd", "Kubernetes"],
  },
  {
    id: "devops-7",
    title: "Automated Chaos Engineering with Chaos Mesh",
    prompt: "Diagram a Kubernetes chaos engineering test pipeline using Chaos Mesh to inject pod kills, network delays, and disk pressure during staging load tests.",
    category: "DevOps",
    complexity: "Advanced",
    tags: ["Chaos Engineering", "Resilience", "ChaosMesh"],
  },
  {
    id: "devops-8",
    title: "Container Security Vulnerability Scanning Pipeline",
    prompt: "Build a DevSecOps CI/CD workflow incorporating Trivy container image scanning, SonarQube static analysis, and Sigstore Cosign cryptographic image signing.",
    category: "DevOps",
    complexity: "Intermediate",
    tags: ["DevSecOps", "Trivy", "Cosign", "Security"],
  },
  {
    id: "devops-9",
    title: "Kubernetes Disaster Recovery with Velero & S3",
    prompt: "Architect an automated backup and disaster recovery topology for stateful Kubernetes clusters using Velero scheduled backups synced to AWS S3 immutable storage.",
    category: "DevOps",
    complexity: "Intermediate",
    tags: ["Velero", "Kubernetes", "Backup", "S3"],
  },
  {
    id: "devops-10",
    title: "Self-Hosted GitHub Actions Runner Autoscaling Fleet",
    prompt: "Design an auto-scaling ephemeral runner fleet for GitHub Actions on Kubernetes using Actions Runner Controller (ARC) with spot instance cost optimization.",
    category: "DevOps",
    complexity: "Advanced",
    tags: ["CI/CD", "GitHub Actions", "ARC", "Runners"],
  },

  // ── 5. Web3 ──
  {
    id: "web3-1",
    title: "Ethereum Layer 2 Optimistic Rollup Decentralized dApp",
    prompt: "Design a full-stack Web3 dApp architecture connecting React Next.js frontend with Arbitrum Layer 2 smart contracts, The Graph indexer, and MetaMask provider.",
    category: "Web3",
    complexity: "Advanced",
    tags: ["Web3", "Arbitrum", "TheGraph", "Ethereum"],
  },
  {
    id: "web3-2",
    title: "Decentralized File Storage with IPFS & Filecoin",
    prompt: "Model an immutable document storage pipeline uploading user media to IPFS nodes, pinning via Pinata/Filecoin, and storing cryptographic CID hashes on smart contracts.",
    category: "Web3",
    complexity: "Intermediate",
    tags: ["IPFS", "Filecoin", "Decentralized", "Storage"],
  },
  {
    id: "web3-3",
    title: "Chainlink Oracle Cross-Chain Asset Bridge",
    prompt: "Architect a cross-chain liquidity bridge leveraging Chainlink CCIP (Cross-Chain Interoperability Protocol) and multi-signature validation for EVM to Solana transfers.",
    category: "Web3",
    complexity: "Enterprise",
    tags: ["Chainlink", "CCIP", "Bridge", "Cross-Chain"],
  },
  {
    id: "web3-4",
    title: "Decentralized Identity (DID) & Verifiable Credentials",
    prompt: "Design a self-sovereign identity architecture using W3C DIDs, Polygon ID zero-knowledge proofs, and off-chain verifiable credentials for compliant user onboarding.",
    category: "Web3",
    complexity: "Advanced",
    tags: ["DID", "Zero Knowledge", "Identity", "Polygon"],
  },
  {
    id: "web3-5",
    title: "NFT Marketplace with Subgraph & Web3 Indexer",
    prompt: "Create an NFT marketplace backend architecture with ERC-721 smart contract events indexed by The Graph, caching metadata on Redis, and rendering through Next.js.",
    category: "Web3",
    complexity: "Intermediate",
    tags: ["NFT", "ERC721", "TheGraph", "NextJS"],
  },
  {
    id: "web3-6",
    title: "Zero-Knowledge Rollup Settlement on Ethereum",
    prompt: "Diagram a ZK-Rollup Layer 2 network showing user transaction aggregation, off-chain SNARK proof generation via GPU prover nodes, and on-chain L1 verifier contracts.",
    category: "Web3",
    complexity: "Enterprise",
    tags: ["ZK-Rollup", "SNARKs", "Layer 2", "Ethereum"],
  },
  {
    id: "web3-7",
    title: "Smart Contract Automated Liquidity Pool (AMM)",
    prompt: "Model an automated market maker (Uniswap v3 style) liquidity pool topology including swap router, concentrated liquidity positions, and TWAP price oracle feeds.",
    category: "Web3",
    complexity: "Advanced",
    tags: ["DeFi", "AMM", "Uniswap", "Solidity"],
  },
  {
    id: "web3-8",
    title: "Multi-Sig DAO Treasury with Safe (Gnosis)",
    prompt: "Architect a decentralized DAO governance infrastructure using Snapshot off-chain gasless voting, Aragon governance smart contracts, and Gnosis Safe multi-signature execution.",
    category: "Web3",
    complexity: "Intermediate",
    tags: ["DAO", "Gnosis Safe", "Governance", "Snapshot"],
  },
  {
    id: "web3-9",
    title: "Account Abstraction (ERC-4337) Smart Wallet System",
    prompt: "Design an Account Abstraction architecture using ERC-4337 EntryPoint contracts, user operation bundler nodes, paymaster gas sponsorship, and social recovery keys.",
    category: "Web3",
    complexity: "Advanced",
    tags: ["ERC4337", "Smart Wallets", "Bundler", "Paymaster"],
  },
  {
    id: "web3-10",
    title: "Crypto Custody Engine with MPC (Multi-Party Computation)",
    prompt: "Diagram an institutional digital asset custody platform utilizing threshold signature schemes (TSS), MPC key share separation, and hardware security modules (HSM).",
    category: "Web3",
    complexity: "Enterprise",
    tags: ["MPC", "Custody", "Security", "HSM"],
  },

  // ── 6. AI & ML ──
  {
    id: "ai-1",
    title: "High-Throughput Vector RAG Pipeline with Gemini",
    prompt: "Design an enterprise Retrieval-Augmented Generation (RAG) system with Google Gemini 2.5 Flash, Pinecone vector database, semantic chunking, and Redis query caching.",
    category: "AI & ML",
    complexity: "Advanced",
    tags: ["RAG", "Gemini", "Pinecone", "Vector"],
  },
  {
    id: "ai-2",
    title: "Autonomous Multi-Agent AI Workflow with LangGraph",
    prompt: "Architect an autonomous multi-agent software development pipeline with specialized Planner, Coder, Reviewer, and QA agents communicating over asynchronous message buses.",
    category: "AI & ML",
    complexity: "Advanced",
    tags: ["AI Agents", "LangGraph", "Multi-Agent", "LLM"],
  },
  {
    id: "ai-3",
    title: "Real-Time Speech-to-Text & Voice AI Assistant",
    prompt: "Design a sub-second voice AI pipeline using WebSocket audio streaming, Deepgram Whisper STT, Gemini Flash streaming token generation, and ElevenLabs TTS output.",
    category: "AI & ML",
    complexity: "Intermediate",
    tags: ["Voice AI", "Whisper", "ElevenLabs", "WebSockets"],
  },
  {
    id: "ai-4",
    title: "Scalable ML Model Serving with Triton & Kubernetes",
    prompt: "Model an enterprise machine learning inference platform using NVIDIA Triton Inference Server on Kubernetes with GPU autoscaling and model versioning.",
    category: "AI & ML",
    complexity: "Enterprise",
    tags: ["Triton", "GPU", "Inference", "Kubernetes"],
  },
  {
    id: "ai-5",
    title: "Document Ingestion & Hybrid Vector Search Engine",
    prompt: "Create an unstructured document intelligence pipeline using Unstructured.io for OCR parsing, BGE embedding models, hybrid dense-sparse search, and reciprocal rank fusion.",
    category: "AI & ML",
    complexity: "Advanced",
    tags: ["OCR", "Embeddings", "Hybrid Search", "Reranker"],
  },
  {
    id: "ai-6",
    title: "Continuous ML Training Pipeline with Kubeflow & MLflow",
    prompt: "Diagram an automated MLOps continuous training loop using Kubeflow pipelines, Feast feature store, MLflow model registry, and automatic drift detection with Evidently.",
    category: "AI & ML",
    complexity: "Enterprise",
    tags: ["MLOps", "Kubeflow", "MLflow", "Feature Store"],
  },
  {
    id: "ai-7",
    title: "Fine-Tuning Cluster for Open-Source LLMs (DeepSeek/Llama)",
    prompt: "Design an on-premises GPU training cluster for fine-tuning Llama 3 using Ray Train, DeepSpeed ZeRO-3, vLLM inference server, and Hugging Face model registry.",
    category: "AI & ML",
    complexity: "Enterprise",
    tags: ["Fine-Tuning", "Ray", "DeepSpeed", "vLLM"],
  },
  {
    id: "ai-8",
    title: "AI Code Execution Sandbox with Firecracker MicroVMs",
    prompt: "Architect an ultra-secure code generation execution sandbox using AWS Firecracker microVMs launched in under 10ms with strict network egress isolation.",
    category: "AI & ML",
    complexity: "Advanced",
    tags: ["Sandboxing", "Firecracker", "Security", "MicroVM"],
  },
  {
    id: "ai-9",
    title: "Real-Time Semantic Cache for LLM API Cost Reduction",
    prompt: "Design an intelligent semantic caching layer using Qdrant vector database and Redis to intercept duplicate or semantically similar prompts, reducing LLM API costs by 60%.",
    category: "AI & ML",
    complexity: "Intermediate",
    tags: ["Semantic Cache", "Qdrant", "Redis", "Cost Optimization"],
  },
  {
    id: "ai-10",
    title: "Enterprise Prompt Governance & Red-Teaming Guardrails",
    prompt: "Model an LLM security proxy gateway incorporating NeMo Guardrails, Presidio PII redaction, prompt injection detection, and full compliance token auditing.",
    category: "AI & ML",
    complexity: "Advanced",
    tags: ["NeMo Guardrails", "PII Redaction", "LLM Security"],
  },

  // ── 7. Cybersecurity ──
  {
    id: "sec-1",
    title: "Zero-Trust BeyondCorp Remote Access Architecture",
    prompt: "Architect a corporate Zero-Trust Network Access (ZTNA) environment with Cloudflare Access, device posture validation, Okta MFA, and granular microsegmentation.",
    category: "Cybersecurity",
    complexity: "Enterprise",
    tags: ["Zero-Trust", "ZTNA", "Okta", "Cloudflare"],
  },
  {
    id: "sec-2",
    title: "OAuth2 & OIDC Federated Identity Provider",
    prompt: "Design an enterprise Single Sign-On (SSO) authentication system with Keycloak, PKCE authentication flow for SPAs, role-based claims, and multi-factor auth.",
    category: "Cybersecurity",
    complexity: "Intermediate",
    tags: ["OAuth2", "OIDC", "Keycloak", "PKCE"],
  },
  {
    id: "sec-3",
    title: "End-to-End Encrypted Messaging (Signal Protocol)",
    prompt: "Diagram an end-to-end encrypted (E2EE) instant messaging architecture implementing the Double Ratchet Algorithm, X3DH key agreement, and encrypted push notifications.",
    category: "Cybersecurity",
    complexity: "Enterprise",
    tags: ["E2EE", "Cryptography", "Double Ratchet", "Signal"],
  },
  {
    id: "sec-4",
    title: "Cloud Security Posture Management (CSPM) Pipeline",
    prompt: "Design an automated multi-cloud compliance scanning system using CloudQuery to extract cloud asset states into PostgreSQL and run automated CIS benchmark checks.",
    category: "Cybersecurity",
    complexity: "Intermediate",
    tags: ["CSPM", "CIS Benchmarks", "CloudQuery", "Compliance"],
  },
  {
    id: "sec-5",
    title: "DDoS Mitigation & Web Application Firewall (WAF) Topology",
    prompt: "Model a multi-layered DDoS defense architecture with Anycast BGP scrubbing centers, edge rate limiting, reCAPTCHA v3 challenge, and automated IP ban sync.",
    category: "Cybersecurity",
    complexity: "Advanced",
    tags: ["DDoS", "WAF", "Anycast", "BGP"],
  },
  {
    id: "sec-6",
    title: "Hardware Security Module (HSM) Key Management System",
    prompt: "Architect a high-security cryptographic key lifecycle system using AWS CloudHSM with envelope encryption for financial transaction signing.",
    category: "Cybersecurity",
    complexity: "Enterprise",
    tags: ["HSM", "Envelope Encryption", "KMS", "Cryptography"],
  },
  {
    id: "sec-7",
    title: "Automated Incident Response with SOAR & SIEM",
    prompt: "Create a Security Operations Center (SOC) architecture connecting Splunk SIEM alerts to Shuffle SOAR automation workflows for automatic IP quarantine.",
    category: "Cybersecurity",
    complexity: "Advanced",
    tags: ["SIEM", "SOAR", "SOC", "Splunk"],
  },
  {
    id: "sec-8",
    title: "API Security Gateway with OWASP Top 10 Mitigation",
    prompt: "Design an API security shield with Kong Gateway, custom plugins for OpenAPI schema validation, JWT inspection, and automatic protection against BOLA/BFLA attacks.",
    category: "Cybersecurity",
    complexity: "Advanced",
    tags: ["OWASP", "Kong", "API Security", "BOLA"],
  },
  {
    id: "sec-9",
    title: "SPIFFE/SPIRE Workload Identity in Multi-Cloud",
    prompt: "Model a universal cryptographic workload identity framework using SPIFFE and SPIRE agents providing temporary X.509 SVID certificates across AWS and GCP containers.",
    category: "Cybersecurity",
    complexity: "Enterprise",
    tags: ["SPIFFE", "SPIRE", "Workload Identity", "X509"],
  },
  {
    id: "sec-10",
    title: "Data Loss Prevention (DLP) & Tokenization Service",
    prompt: "Architect a high-throughput payment tokenization service that strips raw credit card PAN numbers at the API boundary, substituting non-sensitive deterministic tokens.",
    category: "Cybersecurity",
    complexity: "Enterprise",
    tags: ["DLP", "Tokenization", "PCI-DSS", "Encryption"],
  },

  // ── 8. High-Scale ──
  {
    id: "scale-1",
    title: "Global Video Streaming Platform (Netflix/YouTube scale)",
    prompt: "Design a global adaptive bitrate video streaming system with video chunking encoders, CDN edge origin shields, and HLS/DASH manifest delivery.",
    category: "High-Scale",
    complexity: "Enterprise",
    tags: ["Video Streaming", "HLS", "CDN", "Transcoding"],
  },
  {
    id: "scale-2",
    title: "Real-Time Collaborative Canvas (Figma/Prathomix scale)",
    prompt: "Architect a real-time multiplayer collaborative workspace using WebSockets, Conflict-Free Replicated Data Types (CRDTs / Yjs), and Redis pub/sub backplane.",
    category: "High-Scale",
    complexity: "Advanced",
    tags: ["CRDT", "Yjs", "WebSockets", "Multiplayer"],
  },
  {
    id: "scale-3",
    title: "High-Volume Real-Time Ad Bidding Engine (<50ms SLA)",
    prompt: "Design an ultra-low-latency real-time bidding (RTB) engine in Go/Rust handling 500,000 requests per second with Aerospike in-memory database and 30ms response SLA.",
    category: "High-Scale",
    complexity: "Enterprise",
    tags: ["RTB", "AdTech", "Aerospike", "Low Latency"],
  },
  {
    id: "scale-4",
    title: "URL Shortener & Redirect Engine (1 Billion Links/Day)",
    prompt: "Model a globally distributed URL shortener system using base62 encoding, pre-generated ID ranges via ZooKeeper, and distributed Redis caches handling 99.9% read hits.",
    category: "High-Scale",
    complexity: "Intermediate",
    tags: ["URL Shortener", "Base62", "Redis", "ZooKeeper"],
  },
  {
    id: "scale-5",
    title: "Global IoT Telemetry Ingestion (10 Million Connected Devices)",
    prompt: "Design an IoT platform ingesting sensor metrics over MQTT into EMQX broker clusters, buffering with Apache Pulsar, and persisting into TimescaleDB.",
    category: "High-Scale",
    complexity: "Enterprise",
    tags: ["IoT", "MQTT", "Pulsar", "TimescaleDB"],
  },
  {
    id: "scale-6",
    title: "Real-Time Live Chat Application (Slack/Discord scale)",
    prompt: "Architect a scalable live chat platform featuring presence detection, channel message partitioning in Cassandra, and WebSocket connection multiplexers.",
    category: "High-Scale",
    complexity: "Advanced",
    tags: ["Chat", "WebSockets", "Cassandra", "Presence"],
  },
  {
    id: "scale-7",
    title: "Global Distributed E-Commerce Flash Sale Architecture",
    prompt: "Model a high-concurrency ticket/flash-sale checkout system handling inventory deduction with Redis atomic decommit, queue admission gating, and anti-bot validation.",
    category: "High-Scale",
    complexity: "Enterprise",
    tags: ["Flash Sale", "Redis", "Anti-Bot", "Queues"],
  },
  {
    id: "scale-8",
    title: "Ride-Sharing Geospatial Dispatch System (Uber scale)",
    prompt: "Design a real-time driver dispatch platform using Uber H3 hexagonal spatial indexing, QuadTree location tracking, and Redis geospatial queries.",
    category: "High-Scale",
    complexity: "Enterprise",
    tags: ["Geospatial", "H3", "Uber", "Real-Time"],
  },
  {
    id: "scale-9",
    title: "Global Distributed Search Engine Crawler & Indexer",
    prompt: "Model a web crawler architecture with distributed frontier queues, politeness delay managers, content deduplication hashing, and inverted index builders.",
    category: "High-Scale",
    complexity: "Enterprise",
    tags: ["Crawler", "Search Index", "Distributed", "Big Data"],
  },
  {
    id: "scale-10",
    title: "Global Gaming Leaderboard with Millions of Concurrent Users",
    prompt: "Design a real-time gaming leaderboard system using Redis Sorted Sets (ZADD/ZRANGE), write-behind caching to MySQL, and WebSocket live rank updates.",
    category: "High-Scale",
    complexity: "Intermediate",
    tags: ["Leaderboard", "Redis ZSet", "Gaming", "Real-Time"],
  },

  // ── 9. Serverless ──
  {
    id: "serv-1",
    title: "Event-Driven Serverless Order Processing on AWS",
    prompt: "Build an event-driven serverless workflow using Amazon EventBridge, AWS Step Functions for order state orchestration, Lambda workers, and DynamoDB.",
    category: "Serverless",
    complexity: "Intermediate",
    tags: ["Serverless", "EventBridge", "Step Functions", "Lambda"],
  },
  {
    id: "serv-2",
    title: "Serverless Real-Time Image Resizing & WebP Conversion",
    prompt: "Architect an on-demand image processing pipeline using CloudFront edge functions, AWS Lambda with Sharp library, and S3 caching for automated WebP/AVIF resizing.",
    category: "Serverless",
    complexity: "Beginner",
    tags: ["Images", "Lambda", "CloudFront", "S3"],
  },
  {
    id: "serv-3",
    title: "Vercel Edge Functions with Upstash Redis & Vector",
    prompt: "Design a Next.js App Router application with edge middleware authentication, Upstash Serverless Redis for global rate limiting, and Upstash Vector for search.",
    category: "Serverless",
    complexity: "Intermediate",
    tags: ["NextJS", "Upstash", "Vercel", "Edge"],
  },
  {
    id: "serv-4",
    title: "Serverless Email & Notification Delivery Engine",
    prompt: "Model an omnichannel notification engine with Amazon SNS topics, SQS buffers, Lambda formatters, and delivery dispatch to SES (email), Twilio (SMS), and APNs (push).",
    category: "Serverless",
    complexity: "Intermediate",
    tags: ["Notifications", "SNS", "SQS", "SES"],
  },
  {
    id: "serv-5",
    title: "Serverless Data Extraction & PDF Invoice Parsing",
    prompt: "Create a serverless document parsing pipeline triggering AWS Lambda upon S3 PDF uploads, invoking AWS Textract for OCR tables, and saving structured JSON to Aurora.",
    category: "Serverless",
    complexity: "Intermediate",
    tags: ["Textract", "Lambda", "OCR", "PDF"],
  },
  {
    id: "serv-6",
    title: "Serverless GraphQL API with AWS AppSync & Aurora Serverless",
    prompt: "Design a managed GraphQL service with AWS AppSync, direct DynamoDB/Aurora Serverless resolvers, and Cognito user pool authorization.",
    category: "Serverless",
    complexity: "Advanced",
    tags: ["AppSync", "GraphQL", "Cognito", "Serverless"],
  },
  {
    id: "serv-7",
    title: "Scheduled Serverless Maintenance & Health Check Cron",
    prompt: "Design a cloud health monitoring cron using EventBridge scheduled rules triggering Lambdas to run synthetic HTTP checks and send PagerDuty/Slack alerts on failure.",
    category: "Serverless",
    complexity: "Beginner",
    tags: ["Cron", "EventBridge", "Health Check", "Slack"],
  },
  {
    id: "serv-8",
    title: "Serverless Webhook Fanout with AWS EventBridge Pipes",
    prompt: "Architect an event fanout pipeline that ingests Stripe payment webhooks via API Gateway, filters with EventBridge Pipes, and dispatches to 5 downstream services.",
    category: "Serverless",
    complexity: "Intermediate",
    tags: ["Webhooks", "EventBridge Pipes", "Fanout", "Stripe"],
  },
  {
    id: "serv-9",
    title: "Serverless Multi-Tenant SaaS Backend on AWS",
    prompt: "Model a multi-tenant serverless SaaS architecture utilizing dynamic IAM tenant isolation, pooled DynamoDB tables with tenant_id partition keys, and Cognito multi-tenancy.",
    category: "Serverless",
    complexity: "Enterprise",
    tags: ["SaaS", "Multi-Tenant", "DynamoDB", "Cognito"],
  },
  {
    id: "serv-10",
    title: "Serverless Video Transcoding with AWS MediaConvert",
    prompt: "Design a serverless video workflow where S3 raw video upload triggers Lambda to start an AWS Elemental MediaConvert job generating 1080p, 720p, and 480p HLS playlists.",
    category: "Serverless",
    complexity: "Intermediate",
    tags: ["MediaConvert", "Video", "Lambda", "S3"],
  },

  // ── 10. Fintech ──
  {
    id: "fin-1",
    title: "Stripe Payment Gateway Integration with Webhook Idempotency",
    prompt: "Design a robust Stripe payment processing architecture with client SDK tokenization, server-side idempotency keys, and webhook signature verification.",
    category: "Fintech",
    complexity: "Intermediate",
    tags: ["Stripe", "Payments", "Idempotency", "Webhooks"],
  },
  {
    id: "fin-2",
    title: "Double-Entry Bookkeeping Ledger Engine",
    prompt: "Model an immutable double-entry accounting ledger system ensuring debit-credit balance constraints, audit trails, and distributed ACID transactional guarantees.",
    category: "Fintech",
    complexity: "Enterprise",
    tags: ["Ledger", "Accounting", "Fintech", "ACID"],
  },
  {
    id: "fin-3",
    title: "Real-Time Anti-Money Laundering (AML) & Fraud Detection",
    prompt: "Architect a real-time transaction fraud detection system evaluating incoming card transactions against streaming Flink rules and ML risk scoring models in <80ms.",
    category: "Fintech",
    complexity: "Enterprise",
    tags: ["Fraud Detection", "AML", "Apache Flink", "ML"],
  },
  {
    id: "fin-4",
    title: "Digital Banking Core Architecture (Neobank Platform)",
    prompt: "Diagram a modern neobank core banking topology featuring customer account microservices, transaction authorization engine, payment rails (ACH/SEPA/FasterPayments), and ledger.",
    category: "Fintech",
    complexity: "Enterprise",
    tags: ["Neobank", "Core Banking", "ACH", "SEPA"],
  },
  {
    id: "fin-5",
    title: "High-Frequency Cryptocurrency Matching Engine",
    prompt: "Design an in-memory limit order book (LOB) matching engine in C++/Rust with sequence number replication, FIX protocol gateway, and WebSocket depth book streaming.",
    category: "Fintech",
    complexity: "Enterprise",
    tags: ["Order Book", "Matching Engine", "Crypto", "FIX"],
  },
  {
    id: "fin-6",
    title: "PCI-DSS Compliant Cardholder Data Environment (CDE)",
    prompt: "Architect an isolated PCI-DSS Level 1 compliant cardholder data enclave with dedicated network segmentation, transparent database encryption (TDE), and strict access bastions.",
    category: "Fintech",
    complexity: "Enterprise",
    tags: ["PCI-DSS", "Compliance", "Security", "Encryption"],
  },
  {
    id: "fin-7",
    title: "Subscription Billing & Automated Invoicing Engine",
    prompt: "Model an automated SaaS recurring subscription engine handling tiered metered billing, prorated plan upgrades, payment retry dunning cycles, and PDF invoice generation.",
    category: "Fintech",
    complexity: "Intermediate",
    tags: ["Billing", "Subscriptions", "Invoices", "SaaS"],
  },
  {
    id: "fin-8",
    title: "Cross-Border FX Currency Conversion & Settlement Engine",
    prompt: "Design an FX foreign exchange trading and settlement platform polling real-time currency rates, calculating spreads, and executing netting settlement batches.",
    category: "Fintech",
    complexity: "Advanced",
    tags: ["Forex", "FX", "Currency", "Settlement"],
  },
  {
    id: "fin-9",
    title: "KYC & Automated Identity Verification Pipeline",
    prompt: "Create an automated Know-Your-Customer (KYC) onboarding pipeline integrating government ID document verification, facial liveness biometrics, and sanction watchlist screening.",
    category: "Fintech",
    complexity: "Intermediate",
    tags: ["KYC", "Compliance", "Biometrics", "Identity"],
  },
  {
    id: "fin-10",
    title: "Open Banking PSD2 API with Secure Financial Data Sharing",
    prompt: "Architect an Open Banking PSD2 compliant API gateway enabling authorized third-party providers (TPPs) to access customer account data via mTLS and consent tokens.",
    category: "Fintech",
    complexity: "Enterprise",
    tags: ["Open Banking", "PSD2", "mTLS", "Consent"],
  },
];
