"use client";

import React from "react";
import {
  // Essentials & Flowchart
  Square,
  Circle,
  Diamond,
  Cylinder,
  Cloud,
  Folder,
  StickyNote,
  Type,
  Triangle,
  Hexagon,
  Pentagon,
  Octagon,
  Star,
  Heart,
  Box,
  Package,
  Plus,
  Minus,
  Divide,
  Hash,
  Sun,
  Moon,
  Target,
  Sliders,
  // Cloud & Infra
  Server,
  Cpu,
  Layers,
  HardDrive,
  Globe,
  Terminal,
  Code,
  Bot,
  Workflow,
  Network,
  Smartphone,
  Tablet,
  Laptop,
  Monitor,
  Radio,
  Tv,
  // Database & Storage
  Database,
  Table,
  Archive,
  FolderArchive,
  FileText,
  File,
  Save,
  Search,
  Split,
  Copy,
  // Network & Security
  Shield,
  ShieldCheck,
  ShieldAlert,
  Lock,
  Unlock,
  Key,
  Award,
  Wifi,
  Scale,
  Gauge,
  // Arrows & Flow
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ArrowUpRight,
  ArrowDownRight,
  ArrowLeftRight,
  ArrowUpDown,
  Move,
  CornerDownRight,
  CornerUpLeft,
  RefreshCw,
  Repeat,
  GitBranch,
  GitCommit,
  GitMerge,
  GitFork,
  FastForward,
  // Badges & Symbols
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  Sparkles,
  Flame,
  Zap,
  Flag,
  Bookmark,
  Bell,
  Rocket,
  Bug,
  Wrench,
  Clock,
  User,
  Users,
  Building,
  Building2,
} from "lucide-react";

export type ShapeCategory =
  | "all"
  | "essentials"
  | "flowchart"
  | "cloud"
  | "database"
  | "network"
  | "arrows"
  | "symbols";

export interface ShapeDefinition {
  id: string;
  label: string;
  category: ShapeCategory;
  icon: React.ComponentType<{ className?: string }>;
  color: string;
  shapeStyle: "rectangle" | "circle" | "diamond" | "cylinder" | "cloud" | "folder";
  keywords: string[];
  isDailyUse?: boolean;
}

export const CATEGORY_LABELS: Record<ShapeCategory, string> = {
  all: "All (110+)",
  essentials: "Daily Use ⚡",
  flowchart: "Flowchart & Geometry",
  cloud: "Cloud & Compute",
  database: "Data & Storage",
  network: "Network & Security",
  arrows: "Arrows & Connectors",
  symbols: "Symbols & Team",
};

export const SHAPE_LIBRARY: ShapeDefinition[] = [
  // ─────────────────────────────────────────────────────────────
  // 1. DAILY ESSENTIALS (Top row / frequently used)
  // ─────────────────────────────────────────────────────────────
  {
    id: "rectangle",
    label: "Rectangle",
    category: "essentials",
    icon: Square,
    color: "text-cyan-400",
    shapeStyle: "rectangle",
    keywords: ["box", "rect", "block", "node", "process"],
    isDailyUse: true,
  },
  {
    id: "circle",
    label: "Circle",
    category: "essentials",
    icon: Circle,
    color: "text-emerald-400",
    shapeStyle: "circle",
    keywords: ["endpoint", "round", "api", "node"],
    isDailyUse: true,
  },
  {
    id: "diamond",
    label: "Diamond",
    category: "essentials",
    icon: Diamond,
    color: "text-amber-400",
    shapeStyle: "diamond",
    keywords: ["decision", "router", "branch", "condition"],
    isDailyUse: true,
  },
  {
    id: "cylinder",
    label: "Cylinder DB",
    category: "essentials",
    icon: Cylinder,
    color: "text-blue-400",
    shapeStyle: "cylinder",
    keywords: ["database", "sql", "storage", "postgres"],
    isDailyUse: true,
  },
  {
    id: "cloud",
    label: "Cloud",
    category: "essentials",
    icon: Cloud,
    color: "text-sky-400",
    shapeStyle: "cloud",
    keywords: ["aws", "azure", "gcp", "infra", "internet"],
    isDailyUse: true,
  },
  {
    id: "stickyNote",
    label: "Sticky Note",
    category: "essentials",
    icon: StickyNote,
    color: "text-yellow-400",
    shapeStyle: "rectangle",
    keywords: ["note", "memo", "task", "yellow", "todo"],
    isDailyUse: true,
  },
  {
    id: "text",
    label: "Text Note",
    category: "essentials",
    icon: Type,
    color: "text-rose-400",
    shapeStyle: "rectangle",
    keywords: ["text", "title", "label", "heading", "doc"],
    isDailyUse: true,
  },
  {
    id: "server",
    label: "Server Host",
    category: "essentials",
    icon: Server,
    color: "text-indigo-400",
    shapeStyle: "rectangle",
    keywords: ["host", "compute", "backend", "node", "ec2"],
    isDailyUse: true,
  },
  {
    id: "database",
    label: "Database",
    category: "essentials",
    icon: Database,
    color: "text-cyan-400",
    shapeStyle: "cylinder",
    keywords: ["db", "sql", "nosql", "store", "data"],
    isDailyUse: true,
  },
  {
    id: "triangle",
    label: "Triangle",
    category: "essentials",
    icon: Triangle,
    color: "text-teal-400",
    shapeStyle: "diamond",
    keywords: ["pyramid", "delta", "trig"],
    isDailyUse: true,
  },
  {
    id: "hexagon",
    label: "Hexagon",
    category: "essentials",
    icon: Hexagon,
    color: "text-purple-400",
    shapeStyle: "circle",
    keywords: ["hex", "polygon", "cluster"],
    isDailyUse: true,
  },
  {
    id: "star",
    label: "Star",
    category: "essentials",
    icon: Star,
    color: "text-amber-400",
    shapeStyle: "circle",
    keywords: ["rating", "favorite", "highlight", "milestone"],
    isDailyUse: true,
  },
  {
    id: "arrowRight",
    label: "Arrow Flow",
    category: "essentials",
    icon: ArrowRight,
    color: "text-rose-400",
    shapeStyle: "rectangle",
    keywords: ["arrow", "next", "flow", "direction"],
    isDailyUse: true,
  },
  {
    id: "user",
    label: "User Actor",
    category: "essentials",
    icon: User,
    color: "text-blue-400",
    shapeStyle: "circle",
    keywords: ["user", "actor", "client", "person", "human"],
    isDailyUse: true,
  },
  {
    id: "shield",
    label: "Security Shield",
    category: "essentials",
    icon: Shield,
    color: "text-emerald-400",
    shapeStyle: "rectangle",
    keywords: ["security", "firewall", "auth", "safe"],
    isDailyUse: true,
  },
  {
    id: "layers",
    label: "Layer Queue",
    category: "essentials",
    icon: Layers,
    color: "text-sky-400",
    shapeStyle: "rectangle",
    keywords: ["stack", "queue", "layers", "buffer"],
    isDailyUse: true,
  },
  {
    id: "folder",
    label: "Folder Subnet",
    category: "essentials",
    icon: Folder,
    color: "text-indigo-400",
    shapeStyle: "folder",
    keywords: ["directory", "folder", "subnet", "group"],
    isDailyUse: true,
  },

  // ─────────────────────────────────────────────────────────────
  // 2. FLOWCHART & GEOMETRIC SHAPES
  // ─────────────────────────────────────────────────────────────
  {
    id: "square",
    label: "Square",
    category: "flowchart",
    icon: Square,
    color: "text-cyan-400",
    shapeStyle: "rectangle",
    keywords: ["quad", "box", "square"],
  },
  {
    id: "pentagon",
    label: "Pentagon",
    category: "flowchart",
    icon: Pentagon,
    color: "text-emerald-400",
    shapeStyle: "rectangle",
    keywords: ["penta", "5-sided"],
  },
  {
    id: "octagon",
    label: "Octagon",
    category: "flowchart",
    icon: Octagon,
    color: "text-rose-400",
    shapeStyle: "circle",
    keywords: ["stop", "8-sided", "octagon"],
  },
  {
    id: "heart",
    label: "Heart",
    category: "flowchart",
    icon: Heart,
    color: "text-pink-400",
    shapeStyle: "circle",
    keywords: ["like", "love", "favorite"],
  },
  {
    id: "box",
    label: "3D Box",
    category: "flowchart",
    icon: Box,
    color: "text-amber-400",
    shapeStyle: "rectangle",
    keywords: ["cube", "package", "container"],
  },
  {
    id: "package",
    label: "Package",
    category: "flowchart",
    icon: Package,
    color: "text-indigo-400",
    shapeStyle: "rectangle",
    keywords: ["bundle", "module", "cargo"],
  },
  {
    id: "target",
    label: "Target Dot",
    category: "flowchart",
    icon: Target,
    color: "text-red-400",
    shapeStyle: "circle",
    keywords: ["aim", "goal", "focus", "center"],
  },
  {
    id: "plus",
    label: "Plus Join",
    category: "flowchart",
    icon: Plus,
    color: "text-emerald-400",
    shapeStyle: "circle",
    keywords: ["add", "cross", "union", "join"],
  },
  {
    id: "minus",
    label: "Minus Line",
    category: "flowchart",
    icon: Minus,
    color: "text-amber-400",
    shapeStyle: "rectangle",
    keywords: ["subtract", "divider", "bar"],
  },
  {
    id: "divide",
    label: "Division Node",
    category: "flowchart",
    icon: Divide,
    color: "text-blue-400",
    shapeStyle: "circle",
    keywords: ["ratio", "split", "divide"],
  },
  {
    id: "hash",
    label: "Hash Grid",
    category: "flowchart",
    icon: Hash,
    color: "text-purple-400",
    shapeStyle: "rectangle",
    keywords: ["tag", "number", "matrix"],
  },
  {
    id: "sliders",
    label: "Parameter Sliders",
    category: "flowchart",
    icon: Sliders,
    color: "text-teal-400",
    shapeStyle: "rectangle",
    keywords: ["tuning", "config", "controls"],
  },
  {
    id: "sun",
    label: "Sun Flare",
    category: "flowchart",
    icon: Sun,
    color: "text-amber-400",
    shapeStyle: "circle",
    keywords: ["light", "day", "flare"],
  },
  {
    id: "moon",
    label: "Moon Crescent",
    category: "flowchart",
    icon: Moon,
    color: "text-indigo-400",
    shapeStyle: "circle",
    keywords: ["night", "dark", "crescent"],
  },

  // ─────────────────────────────────────────────────────────────
  // 3. CLOUD & ARCHITECTURE INFRASTRUCTURE
  // ─────────────────────────────────────────────────────────────
  {
    id: "cpu",
    label: "CPU Worker",
    category: "cloud",
    icon: Cpu,
    color: "text-cyan-400",
    shapeStyle: "rectangle",
    keywords: ["processor", "core", "compute", "silicon"],
  },
  {
    id: "globe",
    label: "Global CDN",
    category: "cloud",
    icon: Globe,
    color: "text-emerald-400",
    shapeStyle: "circle",
    keywords: ["edge", "cdn", "world", "internet", "cloudflare"],
  },
  {
    id: "terminal",
    label: "Terminal CLI",
    category: "cloud",
    icon: Terminal,
    color: "text-green-400",
    shapeStyle: "rectangle",
    keywords: ["shell", "console", "bash", "command"],
  },
  {
    id: "code",
    label: "Serverless Lambda",
    category: "cloud",
    icon: Code,
    color: "text-amber-400",
    shapeStyle: "rectangle",
    keywords: ["function", "lambda", "script", "code"],
  },
  {
    id: "bot",
    label: "AI Agent Worker",
    category: "cloud",
    icon: Bot,
    color: "text-purple-400",
    shapeStyle: "rectangle",
    keywords: ["ai", "agent", "robot", "llm", "automation"],
  },
  {
    id: "workflow",
    label: "CI/CD Pipeline",
    category: "cloud",
    icon: Workflow,
    color: "text-blue-400",
    shapeStyle: "rectangle",
    keywords: ["pipeline", "github actions", "automation", "jenkins"],
  },
  {
    id: "network",
    label: "Subnet Network",
    category: "cloud",
    icon: Network,
    color: "text-sky-400",
    shapeStyle: "rectangle",
    keywords: ["lan", "vpc", "subnet", "topology"],
  },
  {
    id: "monitor",
    label: "Web Dashboard",
    category: "cloud",
    icon: Monitor,
    color: "text-rose-400",
    shapeStyle: "rectangle",
    keywords: ["screen", "desktop", "ui", "frontend"],
  },
  {
    id: "laptop",
    label: "Dev Client",
    category: "cloud",
    icon: Laptop,
    color: "text-teal-400",
    shapeStyle: "rectangle",
    keywords: ["macbook", "pc", "developer", "station"],
  },
  {
    id: "smartphone",
    label: "Mobile Client",
    category: "cloud",
    icon: Smartphone,
    color: "text-indigo-400",
    shapeStyle: "rectangle",
    keywords: ["ios", "android", "phone", "app"],
  },
  {
    id: "tablet",
    label: "Tablet Terminal",
    category: "cloud",
    icon: Tablet,
    color: "text-blue-400",
    shapeStyle: "rectangle",
    keywords: ["ipad", "tablet", "kiosk"],
  },
  {
    id: "radio",
    label: "Event Broadcast",
    category: "cloud",
    icon: Radio,
    color: "text-pink-400",
    shapeStyle: "circle",
    keywords: ["stream", "broadcast", "kafka", "pubsub"],
  },
  {
    id: "tv",
    label: "Display Screen",
    category: "cloud",
    icon: Tv,
    color: "text-amber-400",
    shapeStyle: "rectangle",
    keywords: ["kiosk", "monitor", "telemetry"],
  },

  // ─────────────────────────────────────────────────────────────
  // 4. DATA & STORAGE
  // ─────────────────────────────────────────────────────────────
  {
    id: "table",
    label: "Data Table",
    category: "database",
    icon: Table,
    color: "text-blue-400",
    shapeStyle: "rectangle",
    keywords: ["rows", "columns", "spreadsheet", "grid"],
  },
  {
    id: "hardDrive",
    label: "SSD Hard Drive",
    category: "database",
    icon: HardDrive,
    color: "text-cyan-400",
    shapeStyle: "rectangle",
    keywords: ["disk", "storage", "ebs", "nvme"],
  },
  {
    id: "archive",
    label: "S3 Bucket Archive",
    category: "database",
    icon: Archive,
    color: "text-amber-400",
    shapeStyle: "cylinder",
    keywords: ["s3", "glacier", "cold storage", "bucket"],
  },
  {
    id: "folderArchive",
    label: "Directory Archive",
    category: "database",
    icon: FolderArchive,
    color: "text-yellow-400",
    shapeStyle: "folder",
    keywords: ["zip", "backup", "files"],
  },
  {
    id: "fileText",
    label: "Log File Store",
    category: "database",
    icon: FileText,
    color: "text-slate-400",
    shapeStyle: "rectangle",
    keywords: ["log", "document", "spec", "text"],
  },
  {
    id: "file",
    label: "Data Payload",
    category: "database",
    icon: File,
    color: "text-emerald-400",
    shapeStyle: "rectangle",
    keywords: ["json", "xml", "binary", "blob"],
  },
  {
    id: "save",
    label: "Snapshot Save",
    category: "database",
    icon: Save,
    color: "text-sky-400",
    shapeStyle: "rectangle",
    keywords: ["snapshot", "backup", "persist"],
  },
  {
    id: "search",
    label: "Vector Search Index",
    category: "database",
    icon: Search,
    color: "text-purple-400",
    shapeStyle: "circle",
    keywords: ["rag", "elasticsearch", "vector", "index"],
  },
  {
    id: "split",
    label: "Data Shard Split",
    category: "database",
    icon: Split,
    color: "text-rose-400",
    shapeStyle: "diamond",
    keywords: ["partition", "shard", "replicate"],
  },
  {
    id: "copy",
    label: "Read Replica",
    category: "database",
    icon: Copy,
    color: "text-teal-400",
    shapeStyle: "cylinder",
    keywords: ["replica", "mirror", "duplicate"],
  },

  // ─────────────────────────────────────────────────────────────
  // 5. NETWORK & SECURITY
  // ─────────────────────────────────────────────────────────────
  {
    id: "shieldCheck",
    label: "Verified Firewall",
    category: "network",
    icon: ShieldCheck,
    color: "text-emerald-400",
    shapeStyle: "rectangle",
    keywords: ["waf", "approved", "verified", "tls"],
  },
  {
    id: "shieldAlert",
    label: "DDoS Protector",
    category: "network",
    icon: ShieldAlert,
    color: "text-rose-400",
    shapeStyle: "rectangle",
    keywords: ["threat", "attack", "alert", "ddos"],
  },
  {
    id: "lock",
    label: "Private Vault",
    category: "network",
    icon: Lock,
    color: "text-amber-400",
    shapeStyle: "rectangle",
    keywords: ["encrypt", "closed", "private", "secret"],
  },
  {
    id: "unlock",
    label: "Public Gateway",
    category: "network",
    icon: Unlock,
    color: "text-green-400",
    shapeStyle: "rectangle",
    keywords: ["open", "public", "ingress"],
  },
  {
    id: "key",
    label: "API Secret Key",
    category: "network",
    icon: Key,
    color: "text-yellow-400",
    shapeStyle: "circle",
    keywords: ["token", "jwt", "apikey", "credential"],
  },
  {
    id: "award",
    label: "SSL Certificate",
    category: "network",
    icon: Award,
    color: "text-indigo-400",
    shapeStyle: "circle",
    keywords: ["cert", "badge", "ssl", "https"],
  },
  {
    id: "wifi",
    label: "WiFi Hotspot",
    category: "network",
    icon: Wifi,
    color: "text-sky-400",
    shapeStyle: "circle",
    keywords: ["wireless", "signal", "radio", "iot"],
  },
  {
    id: "scale",
    label: "Load Balancer",
    category: "network",
    icon: Scale,
    color: "text-purple-400",
    shapeStyle: "diamond",
    keywords: ["alb", "nlb", "balancer", "traffic"],
  },
  {
    id: "gauge",
    label: "Rate Limiter",
    category: "network",
    icon: Gauge,
    color: "text-cyan-400",
    shapeStyle: "circle",
    keywords: ["throttle", "speed", "metric", "quota"],
  },

  // ─────────────────────────────────────────────────────────────
  // 6. ARROWS & FLOW CONNECTORS
  // ─────────────────────────────────────────────────────────────
  {
    id: "arrowLeft",
    label: "Arrow Left",
    category: "arrows",
    icon: ArrowLeft,
    color: "text-rose-400",
    shapeStyle: "rectangle",
    keywords: ["back", "left", "return"],
  },
  {
    id: "arrowUp",
    label: "Arrow Up",
    category: "arrows",
    icon: ArrowUp,
    color: "text-cyan-400",
    shapeStyle: "rectangle",
    keywords: ["up", "ingress", "top"],
  },
  {
    id: "arrowDown",
    label: "Arrow Down",
    category: "arrows",
    icon: ArrowDown,
    color: "text-amber-400",
    shapeStyle: "rectangle",
    keywords: ["down", "egress", "bottom"],
  },
  {
    id: "arrowUpRight",
    label: "Arrow Up-Right",
    category: "arrows",
    icon: ArrowUpRight,
    color: "text-emerald-400",
    shapeStyle: "rectangle",
    keywords: ["diagonal", "export", "forward"],
  },
  {
    id: "arrowDownRight",
    label: "Arrow Down-Right",
    category: "arrows",
    icon: ArrowDownRight,
    color: "text-purple-400",
    shapeStyle: "rectangle",
    keywords: ["diagonal", "sink", "divert"],
  },
  {
    id: "arrowLeftRight",
    label: "Bidirectional Flow",
    category: "arrows",
    icon: ArrowLeftRight,
    color: "text-blue-400",
    shapeStyle: "rectangle",
    keywords: ["bidirectional", "two-way", "sync"],
  },
  {
    id: "arrowUpDown",
    label: "Vertical Sync",
    category: "arrows",
    icon: ArrowUpDown,
    color: "text-sky-400",
    shapeStyle: "rectangle",
    keywords: ["vertical", "two-way", "duplex"],
  },
  {
    id: "cornerDownRight",
    label: "Curved Route",
    category: "arrows",
    icon: CornerDownRight,
    color: "text-indigo-400",
    shapeStyle: "rectangle",
    keywords: ["turn", "curve", "route"],
  },
  {
    id: "cornerUpLeft",
    label: "Return Curve",
    category: "arrows",
    icon: CornerUpLeft,
    color: "text-teal-400",
    shapeStyle: "rectangle",
    keywords: ["turn", "loop", "return"],
  },
  {
    id: "refreshCw",
    label: "Cycle Loop",
    category: "arrows",
    icon: RefreshCw,
    color: "text-cyan-400",
    shapeStyle: "circle",
    keywords: ["refresh", "loop", "cron", "sync"],
  },
  {
    id: "repeat",
    label: "Repeat Loop",
    category: "arrows",
    icon: Repeat,
    color: "text-amber-400",
    shapeStyle: "rectangle",
    keywords: ["repeat", "loop", "interval"],
  },
  {
    id: "move",
    label: "4-Way Dispatch",
    category: "arrows",
    icon: Move,
    color: "text-rose-400",
    shapeStyle: "diamond",
    keywords: ["move", "multi-direction", "dispatch"],
  },
  {
    id: "gitBranch",
    label: "Git Branch",
    category: "arrows",
    icon: GitBranch,
    color: "text-emerald-400",
    shapeStyle: "rectangle",
    keywords: ["fork", "branch", "vcs"],
  },
  {
    id: "gitCommit",
    label: "Git Commit",
    category: "arrows",
    icon: GitCommit,
    color: "text-blue-400",
    shapeStyle: "circle",
    keywords: ["commit", "version", "checkpoint"],
  },
  {
    id: "gitMerge",
    label: "Git Merge",
    category: "arrows",
    icon: GitMerge,
    color: "text-purple-400",
    shapeStyle: "rectangle",
    keywords: ["merge", "join", "integrate"],
  },
  {
    id: "gitFork",
    label: "Git Fork",
    category: "arrows",
    icon: GitFork,
    color: "text-yellow-400",
    shapeStyle: "diamond",
    keywords: ["split", "fork", "separate"],
  },
  {
    id: "fastForward",
    label: "Fast Forward",
    category: "arrows",
    icon: FastForward,
    color: "text-cyan-400",
    shapeStyle: "rectangle",
    keywords: ["skip", "fast", "speed"],
  },

  // ─────────────────────────────────────────────────────────────
  // 7. SYMBOLS, BADGES & COLLABORATION
  // ─────────────────────────────────────────────────────────────
  {
    id: "checkCircle2",
    label: "Success Check",
    category: "symbols",
    icon: CheckCircle2,
    color: "text-emerald-400",
    shapeStyle: "circle",
    keywords: ["ok", "pass", "good", "done"],
  },
  {
    id: "xCircle",
    label: "Error Cross",
    category: "symbols",
    icon: XCircle,
    color: "text-rose-400",
    shapeStyle: "circle",
    keywords: ["fail", "error", "bad", "cancel"],
  },
  {
    id: "alertTriangle",
    label: "Warning Alert",
    category: "symbols",
    icon: AlertTriangle,
    color: "text-amber-400",
    shapeStyle: "diamond",
    keywords: ["caution", "warning", "danger"],
  },
  {
    id: "info",
    label: "Info Badge",
    category: "symbols",
    icon: Info,
    color: "text-blue-400",
    shapeStyle: "circle",
    keywords: ["information", "detail", "about"],
  },
  {
    id: "helpCircle",
    label: "Help Question",
    category: "symbols",
    icon: HelpCircle,
    color: "text-teal-400",
    shapeStyle: "circle",
    keywords: ["question", "support", "faq"],
  },
  {
    id: "sparkles",
    label: "AI Sparkles",
    category: "symbols",
    icon: Sparkles,
    color: "text-purple-400",
    shapeStyle: "circle",
    keywords: ["ai", "magic", "smart", "gemini"],
  },
  {
    id: "flame",
    label: "Hotspot Flame",
    category: "symbols",
    icon: Flame,
    color: "text-orange-400",
    shapeStyle: "diamond",
    keywords: ["fire", "hot", "critical"],
  },
  {
    id: "zap",
    label: "High Priority Zap",
    category: "symbols",
    icon: Zap,
    color: "text-yellow-400",
    shapeStyle: "diamond",
    keywords: ["flash", "fast", "urgent", "electric"],
  },
  {
    id: "flag",
    label: "Project Milestone",
    category: "symbols",
    icon: Flag,
    color: "text-red-400",
    shapeStyle: "rectangle",
    keywords: ["goal", "target", "milestone"],
  },
  {
    id: "bookmark",
    label: "Bookmark Anchor",
    category: "symbols",
    icon: Bookmark,
    color: "text-indigo-400",
    shapeStyle: "rectangle",
    keywords: ["save", "favorite", "pin"],
  },
  {
    id: "bell",
    label: "Notification Bell",
    category: "symbols",
    icon: Bell,
    color: "text-amber-400",
    shapeStyle: "circle",
    keywords: ["alert", "notify", "ping"],
  },
  {
    id: "rocket",
    label: "Production Launch",
    category: "symbols",
    icon: Rocket,
    color: "text-rose-400",
    shapeStyle: "circle",
    keywords: ["launch", "deploy", "release", "ship"],
  },
  {
    id: "bug",
    label: "Bug Defect",
    category: "symbols",
    icon: Bug,
    color: "text-red-400",
    shapeStyle: "circle",
    keywords: ["defect", "issue", "error"],
  },
  {
    id: "wrench",
    label: "Config Wrench",
    category: "symbols",
    icon: Wrench,
    color: "text-slate-400",
    shapeStyle: "rectangle",
    keywords: ["tools", "repair", "service"],
  },
  {
    id: "clock",
    label: "SLA Timer Clock",
    category: "symbols",
    icon: Clock,
    color: "text-cyan-400",
    shapeStyle: "circle",
    keywords: ["time", "delay", "latency", "schedule"],
  },
  {
    id: "users",
    label: "Engineering Team",
    category: "symbols",
    icon: Users,
    color: "text-blue-400",
    shapeStyle: "circle",
    keywords: ["team", "org", "group", "people"],
  },
  {
    id: "building",
    label: "Datacenter Building",
    category: "symbols",
    icon: Building,
    color: "text-emerald-400",
    shapeStyle: "rectangle",
    keywords: ["enterprise", "office", "datacenter"],
  },
  {
    id: "building2",
    label: "HQ Facility",
    category: "symbols",
    icon: Building2,
    color: "text-sky-400",
    shapeStyle: "rectangle",
    keywords: ["corp", "company", "headquarters"],
  },
];
